
package com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EfacturaService", targetNamespace = "http://ws.broker.fact.praxis.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EfacturaService {


    /**
     * 
     * @param comprobanteCFDI
     * @param credenciales
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "generar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emitirCFDIv32", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirCFDIv32")
    @ResponseWrapper(localName = "emitirCFDIv32Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirCFDIv32Response")
    public String emitirCFDIv32(
        @WebParam(name = "comprobanteCFDI", targetNamespace = "")
        ComprobanteCFDIv32 comprobanteCFDI,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param credenciales
     * @param comprobanteCFDIv33
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "generar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emitirCFDIv33", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirCFDIv33")
    @ResponseWrapper(localName = "emitirCFDIv33Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirCFDIv33Response")
    public String emitirCFDIv33(
        @WebParam(name = "comprobanteCFDIv33", targetNamespace = "")
        ComprobanteCFDIv33 comprobanteCFDIv33,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param comprobanteRetenciones
     * @param credenciales
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "generar-comprobante-retenciones")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emitirRetenciones", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirRetenciones")
    @ResponseWrapper(localName = "emitirRetencionesResponse", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirRetencionesResponse")
    public String emitirRetenciones(
        @WebParam(name = "comprobanteRetenciones", targetNamespace = "")
        ComprobanteRetenciones comprobanteRetenciones,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param credenciales
     * @return
     *     returns com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ApiConsultaRecepcionResponse
     */
    @WebMethod(action = "recepcion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarComprobantesRecepcion", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ConsultarComprobantesRecepcion")
    @ResponseWrapper(localName = "consultarComprobantesRecepcionResponse", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ConsultarComprobantesRecepcionResponse")
    public ApiConsultaRecepcionResponse consultarComprobantesRecepcion(
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param uuid
     * @param credenciales
     * @return
     *     returns com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ApiCancelResponse
     */
    @WebMethod(action = "cancelar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelarCFDIv33", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.CancelarCFDIv33")
    @ResponseWrapper(localName = "cancelarCFDIv33Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.CancelarCFDIv33Response")
    public ApiCancelResponse cancelarCFDIv33(
        @WebParam(name = "uuid", targetNamespace = "")
        List<String> uuid,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param uuid
     * @param credenciales
     * @return
     *     returns com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ApiCancelResponse
     */
    @WebMethod(action = "cancelar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelarCFDIv32", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.CancelarCFDIv32")
    @ResponseWrapper(localName = "cancelarCFDIv32Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.CancelarCFDIv32Response")
    public ApiCancelResponse cancelarCFDIv32(
        @WebParam(name = "uuid", targetNamespace = "")
        List<String> uuid,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param uuid
     * @param credenciales
     * @return
     *     returns com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ApiConsultaResponse
     */
    @WebMethod(action = "consultar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultarCFDIv32", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ConsultarCFDIv32")
    @ResponseWrapper(localName = "consultarCFDIv32Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ConsultarCFDIv32Response")
    public ApiConsultaResponse consultarCFDIv32(
        @WebParam(name = "uuid", targetNamespace = "")
        List<String> uuid,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param rfcEmpresa
     * @param nombreSucursal
     * @param rfcCliente
     * @param usoCFDI
     * @param numeroTicket
     * @return
     *     returns com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.RespuestaFacturaDTO
     */
    @WebMethod(action = "generar-comprobante-YoFacturo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generacionFacturaYoFacturo", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.GeneracionFacturaYoFacturo")
    @ResponseWrapper(localName = "generacionFacturaYoFacturoResponse", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.GeneracionFacturaYoFacturoResponse")
    public RespuestaFacturaDTO generacionFacturaYoFacturo(
        @WebParam(name = "rfcEmpresa", targetNamespace = "")
        String rfcEmpresa,
        @WebParam(name = "numeroTicket", targetNamespace = "")
        String numeroTicket,
        @WebParam(name = "rfcCliente", targetNamespace = "")
        String rfcCliente,
        @WebParam(name = "nombreSucursal", targetNamespace = "")
        String nombreSucursal,
        @WebParam(name = "usoCFDI", targetNamespace = "")
        String usoCFDI);

    /**
     * 
     * @param usuNombre
     * @param pass
     * @param credenciales
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "actualiza-contra-usuario")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizarContra", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ActualizarContra")
    @ResponseWrapper(localName = "actualizarContraResponse", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ActualizarContraResponse")
    public String actualizarContra(
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales,
        @WebParam(name = "usuNombre", targetNamespace = "")
        String usuNombre,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * 
     * @param comprobanteRetencionesV20
     * @param credenciales
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "generar-comprobante-retenciones")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emitirRetencionesV20", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirRetencionesV20")
    @ResponseWrapper(localName = "emitirRetencionesV20Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirRetencionesV20Response")
    public String emitirRetencionesV20(
        @WebParam(name = "comprobanteRetencionesV20", targetNamespace = "")
        ComprobanteRetencionesV20 comprobanteRetencionesV20,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param folios
     * @param credenciales
     * @return
     *     returns com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.ApiCancelResponse
     */
    @WebMethod(action = "cancelar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelarCFDIv40", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.CancelarCFDIv40")
    @ResponseWrapper(localName = "cancelarCFDIv40Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.CancelarCFDIv40Response")
    public ApiCancelResponse cancelarCFDIv40(
        @WebParam(name = "folios", targetNamespace = "")
        Folios folios,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

    /**
     * 
     * @param comprobanteCFDIv40
     * @param credenciales
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "generar-comprobante")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "emitirCFDIv40", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirCFDIv40")
    @ResponseWrapper(localName = "emitirCFDIv40Response", targetNamespace = "http://ws.broker.fact.praxis.com/", className = "com.mx.mex.Webservices.Soap.com.praxis.fact.broker.ws.com.praxis.fact.broker.ws.EmitirCFDIv40Response")
    public String emitirCFDIv40(
        @WebParam(name = "comprobanteCFDIv40", targetNamespace = "")
        ComprobanteCFDIv40 comprobanteCFDIv40,
        @WebParam(name = "credenciales", targetNamespace = "")
        Credenciales credenciales);

}
